# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.api.curve_api import CurveApi


class TestCurveApi(unittest.TestCase):
    """CurveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurveApi()

    def tearDown(self) -> None:
        pass

    def test_delete_curve(self) -> None:
        """Test case for delete_curve

        Delete Curve
        """
        pass

    def test_get_all_curve_data_points(self) -> None:
        """Test case for get_all_curve_data_points

        Get Curve Data Points
        """
        pass

    def test_get_curve_data_point(self) -> None:
        """Test case for get_curve_data_point

        Get Curve Data Point
        """
        pass

    def test_get_curve_header(self) -> None:
        """Test case for get_curve_header

        Get Curve Header
        """
        pass

    def test_set_curve_data_point(self) -> None:
        """Test case for set_curve_data_point

        Set Curve Data Point
        """
        pass

    def test_set_curve_header(self) -> None:
        """Test case for set_curve_header

        Set Curve Header
        """
        pass


if __name__ == '__main__':
    unittest.main()
