# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.identification_resp import IdentificationResp

class TestIdentificationResp(unittest.TestCase):
    """IdentificationResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentificationResp:
        """Test IdentificationResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentificationResp`
        """
        model = IdentificationResp()
        if include_optional:
            return IdentificationResp(
                manufacturer = '',
                model = '',
                serial_number = '',
                firmware_version = ''
            )
        else:
            return IdentificationResp(
                manufacturer = '',
                model = '',
                serial_number = '',
                firmware_version = '',
        )
        """

    def testIdentificationResp(self):
        """Test IdentificationResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
