# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.coefficients import Coefficients

class TestCoefficients(unittest.TestCase):
    """Coefficients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoefficients(self):
        """Test Coefficients"""
        # inst = Coefficients()

if __name__ == '__main__':
    unittest.main()
