# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.status_resp import StatusResp

class TestStatusResp(unittest.TestCase):
    """StatusResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusResp:
        """Test StatusResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusResp`
        """
        model = StatusResp()
        if include_optional:
            return StatusResp(
                invalid_reading = True,
                temp_under_range = True,
                temp_over_range = True,
                sensor_units_over_range = True,
                sensor_units_under_range = True
            )
        else:
            return StatusResp(
                invalid_reading = True,
                temp_under_range = True,
                temp_over_range = True,
                sensor_units_over_range = True,
                sensor_units_under_range = True,
        )
        """

    def testStatusResp(self):
        """Test StatusResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
