# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.sensor_types import SensorTypes

class TestSensorTypes(unittest.TestCase):
    """SensorTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensorTypes(self):
        """Test SensorTypes"""
        # inst = SensorTypes()

if __name__ == '__main__':
    unittest.main()
