# coding: utf-8

"""
    Lakeshore Management API (LT Capstone)

    API server that manages Lakeshore devices and exports metrics via REST API.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.units import Units

class TestUnits(unittest.TestCase):
    """Units unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnits(self):
        """Test Units"""
        # inst = Units()

if __name__ == '__main__':
    unittest.main()
