# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.curve_data_point import CurveDataPoint

class TestCurveDataPoint(unittest.TestCase):
    """CurveDataPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurveDataPoint:
        """Test CurveDataPoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurveDataPoint`
        """
        model = CurveDataPoint()
        if include_optional:
            return CurveDataPoint(
                temperature = 1.337,
                sensor = 1.337
            )
        else:
            return CurveDataPoint(
                temperature = 1.337,
                sensor = 1.337,
        )
        """

    def testCurveDataPoint(self):
        """Test CurveDataPoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
