# coding: utf-8

"""
    Lakeshore Management API (LT Capstone)

    API server that manages Lakeshore devices and exports metrics via REST API.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.monitor_resp import MonitorResp

class TestMonitorResp(unittest.TestCase):
    """MonitorResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorResp:
        """Test MonitorResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MonitorResp`
        """
        model = MonitorResp()
        if include_optional:
            return MonitorResp(
                kelvin = 1.337,
                sensor = 1.337
            )
        else:
            return MonitorResp(
                kelvin = 1.337,
                sensor = 1.337,
        )
        """

    def testMonitorResp(self):
        """Test MonitorResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
