# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.api.reading_api import ReadingApi


class TestReadingApi(unittest.TestCase):
    """ReadingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ReadingApi()

    def tearDown(self) -> None:
        pass

    def test_get_input_parameter(self) -> None:
        """Test case for get_input_parameter

        Get Input Parameter
        """
        pass

    def test_get_monitor(self) -> None:
        """Test case for get_monitor

        Get Monitor
        """
        pass

    def test_set_input_parameter(self) -> None:
        """Test case for set_input_parameter

        Set Input Config
        """
        pass


if __name__ == '__main__':
    unittest.main()
