# coding: utf-8

"""
    Lakeshore Management API (LT Capstone)

    API server that manages Lakeshore devices and exports metrics via REST API.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.models.set_curve_data_points_request import SetCurveDataPointsRequest

class TestSetCurveDataPointsRequest(unittest.TestCase):
    """SetCurveDataPointsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetCurveDataPointsRequest:
        """Test SetCurveDataPointsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetCurveDataPointsRequest`
        """
        model = SetCurveDataPointsRequest()
        if include_optional:
            return SetCurveDataPointsRequest(
                data_points = [
                    lgg_client.models.curve_data_point.CurveDataPoint(
                        temperature = 1.337, 
                        sensor = 1.337, )
                    ]
            )
        else:
            return SetCurveDataPointsRequest(
                data_points = [
                    lgg_client.models.curve_data_point.CurveDataPoint(
                        temperature = 1.337, 
                        sensor = 1.337, )
                    ],
        )
        """

    def testSetCurveDataPointsRequest(self):
        """Test SetCurveDataPointsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
