# coding: utf-8

"""
    Lakeshore Management API (LT Capstone)

    API server that manages Lakeshore devices and exports metrics via REST API.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lgg_client.api.device_api import DeviceApi


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeviceApi()

    def tearDown(self) -> None:
        pass

    def test_connect(self) -> None:
        """Test case for connect

        Connect
        """
        pass

    def test_disconnect(self) -> None:
        """Test case for disconnect

        Disconnect
        """
        pass

    def test_get_brightness(self) -> None:
        """Test case for get_brightness

        Get Brightness
        """
        pass

    def test_get_identification(self) -> None:
        """Test case for get_identification

        Get Identification
        """
        pass

    def test_get_module_name(self) -> None:
        """Test case for get_module_name

        Get Modname
        """
        pass

    def test_get_status(self) -> None:
        """Test case for get_status

        Get Status
        """
        pass

    def test_set_brightness(self) -> None:
        """Test case for set_brightness

        Set Brightness
        """
        pass

    def test_set_factory_defaults(self) -> None:
        """Test case for set_factory_defaults

        Set Factory Defaults
        """
        pass

    def test_set_module_name(self) -> None:
        """Test case for set_module_name

        Set Modname
        """
        pass


if __name__ == '__main__':
    unittest.main()
