services:
  tsdb:
    image: timescale/timescaledb:latest-pg17
    container_name: rice-tsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lt-capstone
    ports:
      - "5432:5432"
    volumes:
      - tsdb-data:/var/lib/postgresql/data

  dashboard:
    image: grafana/grafana:latest
    container_name: rice-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    container_name: rice-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./otel/tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: rice-otel
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel/otel-config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - tempo

volumes:
  tsdb-data:
    driver: local
    name: rice-tsdb-data
  grafana_data:
    driver: local
    name: rice-grafana-data
  tempo_data:
    driver: local
    name: rice-tempo-data

networks:
  default:
    name: rice-shower
    driver: bridge
