services:
  tsdb:
    image: timescale/timescaledb:latest-pg17
    container_name: rice-tsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lt-capstone
    ports:
      - "5432:5432"
    volumes:
      - tsdb-data:/var/lib/postgresql/data

  dashboard:
    image: grafana/grafana:latest
    container_name: rice-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  tsdb-data:
    driver: local
    name: rice-tsdb-data
  grafana_data:
    driver: local
    name: rice-grafana-data

networks:
  default:
    name: rice-shower
    driver: bridge
