# coding: utf-8

# flake8: noqa

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.0"

# Define package exports
__all__ = [
    "SimulatorApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "GetSimulatorTemperature200Response",
    "GetSimulatorTemperature404Response",
    "SetHeaterOutput200Response",
    "SetHeaterOutput404Response",
    "SetHeaterOutputRequest",
]

# import apis into sdk package
from simulator_client.api.simulator_api import SimulatorApi as SimulatorApi

# import ApiClient
from simulator_client.api_response import ApiResponse as ApiResponse
from simulator_client.api_client import ApiClient as ApiClient
from simulator_client.configuration import Configuration as Configuration
from simulator_client.exceptions import OpenApiException as OpenApiException
from simulator_client.exceptions import ApiTypeError as ApiTypeError
from simulator_client.exceptions import ApiValueError as ApiValueError
from simulator_client.exceptions import ApiKeyError as ApiKeyError
from simulator_client.exceptions import ApiAttributeError as ApiAttributeError
from simulator_client.exceptions import ApiException as ApiException

# import models into sdk package
from simulator_client.models.get_simulator_temperature200_response import GetSimulatorTemperature200Response as GetSimulatorTemperature200Response
from simulator_client.models.get_simulator_temperature404_response import GetSimulatorTemperature404Response as GetSimulatorTemperature404Response
from simulator_client.models.set_heater_output200_response import SetHeaterOutput200Response as SetHeaterOutput200Response
from simulator_client.models.set_heater_output404_response import SetHeaterOutput404Response as SetHeaterOutput404Response
from simulator_client.models.set_heater_output_request import SetHeaterOutputRequest as SetHeaterOutputRequest

