/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/temp/target-temp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Target Temp
     * @description Get the current target temperature.
     */
    get: operations["getTargetTemp"];
    put?: never;
    /**
     * Set Target
     * @description Set a new target temperature.
     */
    post: operations["setTargetTemp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/temp/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Status
     * @description Get the current temperature status.
     */
    get: operations["getStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/temp/parameters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Parameters
     * @description Get the current temperature PID parameters.
     */
    get: operations["getParameters"];
    put?: never;
    /**
     * Set Parameters
     * @description Update PID parameters.
     */
    post: operations["setParameters"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Parameters
     * @description Schema for temperature parameters.
     *
     *     Used by GET and PUT /temp/parameters endpoints
     *     to retrieve or update temperature parameters.
     */
    Parameters: {
      /**
       * Kp
       * @default 1
       */
      kp: number;
      /**
       * Ki
       * @default 0
       */
      ki: number;
      /**
       * Kd
       * @default 0
       */
      kd: number;
    };
    /**
     * StatusOut
     * @description Schema for temperature status.
     *
     *     Used by GET /temp/status endpoints
     *     to retrieve or update temperature status.
     */
    StatusOut: {
      /** Target */
      target: number;
      /** Dutycycle */
      dutyCycle: number;
    };
    /**
     * TargetTemp
     * @description Schema for target temperature.
     *
     *     Used by GET and PUT /temp/target-temp endpoints
     *     to retrieve or update target temperature.
     */
    TargetTemp: {
      /** Target */
      target: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getTargetTemp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TargetTemp"];
        };
      };
    };
  };
  setTargetTemp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetTemp"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StatusOut"];
        };
      };
    };
  };
  getParameters: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Parameters"];
        };
      };
    };
  };
  setParameters: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Parameters"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Parameters"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
