/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/channels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Channels
     * @description List all configured channels from config.yaml.
     *
     *     Returns information about all channels including their configuration
     *     and current runtime status (whether PID is active).
     */
    get: operations["listChannels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{channel_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Channel Info
     * @description Get information about a specific channel.
     *
     *     Returns configuration and runtime status for the specified channel.
     */
    get: operations["getChannelInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/status/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Channels Status
     * @description Get comprehensive PID status for all enabled channels at once.
     *
     *     Returns detailed PID status including temperature, duty cycle, parameters,
     *     and error statistics for each enabled channel.
     */
    get: operations["getAllChannelsStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/{channel_id}/target-temp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Target Temp
     * @description Get the current target temperature for a specific channel.
     */
    get: operations["getTargetTemp"];
    put?: never;
    /**
     * Set Target Temp
     * @description Set a new target temperature for a specific channel.
     */
    post: operations["setTargetTemp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/{channel_id}/pid-parameters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pid Parameters
     * @description Get the current PID parameters for a specific channel.
     */
    get: operations["getPidParameters"];
    put?: never;
    /**
     * Set Pid Parameters
     * @description Update PID parameters for a specific channel.
     */
    post: operations["setPidParameters"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/{channel_id}/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Config
     * @description Get all configuration (target temperature and PID parameters) for a specific channel.
     */
    get: operations["getAllConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pid/{channel_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Pid
     * @description Start the PID controller for a specific channel.
     */
    post: operations["startPID"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pid/{channel_id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stop Pid
     * @description Stop the PID controller for a specific channel.
     */
    post: operations["stopPID"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pid/{channel_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pid Status
     * @description Get comprehensive PID status for a specific channel.
     *
     *     Returns:
     *     - channel_id: Channel identifier
     *     - channel_name: Channel name
     *     - is_active: Whether PID controller is currently running
     *     - target: Target temperature
     *     - power: Current heater output power (0.0 to 1.0)
     *     - max_heater_power_watts: Maximum heater power rating in watts
     *     - current_temp: Current temperature reading
     *     - pid_parameters: Current PID coefficients (Kp, Ki, Kd)
     *     - pid_variables: Internal PID variables (integral, last_error, last_measurement)
     *     - error_stats: Error statistics including counts for last 1m, 10m, and since start
     */
    get: operations["getPidStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AllChannelsStatus
     * @description Status of all channels at once.
     */
    AllChannelsStatus: {
      /** Channels */
      channels: components["schemas"]["PidStatusOut"][];
    };
    /**
     * ChannelInfo
     * @description Channel information with runtime status.
     */
    ChannelInfo: {
      /** Channelid */
      channelId: number;
      /** Name */
      name: string;
      /** Gpiopin */
      gpioPin: number;
      /** Sensorchannel */
      sensorChannel: number;
      /** Enabled */
      enabled: boolean;
      /**
       * Maxheaterpowerwatts
       * @description Maximum heater power in watts
       */
      maxHeaterPowerWatts: number;
      /**
       * Isactive
       * @description Whether PID controller is currently active
       * @default false
       */
      isActive: boolean;
    };
    /**
     * ChannelListResponse
     * @description List of all configured channels.
     */
    ChannelListResponse: {
      /** Channels */
      channels: components["schemas"]["ChannelInfo"][];
    };
    /**
     * ConfigAll
     * @description Schema for all configuration data.
     *
     *     Contains target temperature and PID parameters.
     */
    ConfigAll: {
      /** Targettemp */
      targetTemp: number;
      pidParameters: components["schemas"]["Parameters"];
    };
    /**
     * ErrorStats
     * @description Schema for error statistics.
     *
     *     Tracks API call errors over different time periods.
     */
    ErrorStats: {
      /** Errorslast1M */
      errorsLast1M: number;
      /** Errorslast10M */
      errorsLast10M: number;
      /** Errorssincestart */
      errorsSinceStart: number;
      /** Lasterrormessage */
      lastErrorMessage: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * Parameters
     * @description Schema for temperature parameters.
     *
     *     Used by GET and PUT /temp/parameters endpoints
     *     to retrieve or update temperature parameters.
     */
    Parameters: {
      /**
       * Kp
       * @default 1
       */
      kp: number;
      /**
       * Ki
       * @default 0
       */
      ki: number;
      /**
       * Kd
       * @default 0
       */
      kd: number;
    };
    /**
     * PidStatusOut
     * @description Schema for PID status output.
     *
     *     Contains comprehensive information about PID controller state.
     */
    PidStatusOut: {
      /** Channelid */
      channelId: number;
      /** Channelname */
      channelName: string;
      /** Isactive */
      isActive: boolean;
      /** Target */
      target: number;
      /** Power */
      power: number;
      /** Maxheaterpowerwatts */
      maxHeaterPowerWatts: number;
      /** Currenttemp */
      currentTemp: number | null;
      /** Startedat */
      startedAt: string | null;
      /** Runningforseconds */
      runningForSeconds: number | null;
      pidParameters: components["schemas"]["Parameters"];
      pidVariables: components["schemas"]["PidVariables"];
      errorStats: components["schemas"]["ErrorStats"];
    };
    /**
     * PidVariables
     * @description Schema for PID internal variables.
     *
     *     Contains the interval variables used in PID calculations.
     */
    PidVariables: {
      /** Integral */
      integral: number;
      /** Lasterror */
      lastError: number;
      /** Lastmeasurement */
      lastMeasurement: number | null;
    };
    /**
     * TargetTemp
     * @description Schema for target temperature.
     *
     *     Used by GET and PUT /temp/target-temp endpoints
     *     to retrieve or update target temperature.
     */
    TargetTemp: {
      /** Target */
      target: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listChannels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelListResponse"];
        };
      };
    };
  };
  getChannelInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getAllChannelsStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AllChannelsStatus"];
        };
      };
    };
  };
  getTargetTemp: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TargetTemp"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  setTargetTemp: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetTemp"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getPidParameters: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Parameters"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  setPidParameters: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Parameters"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Parameters"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getAllConfig: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigAll"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  startPID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stopPID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getPidStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PidStatusOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
