/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/channels": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Channels
     * @description List all configured channels from config.yaml.
     *
     *     Returns information about all channels including their configuration
     *     and current runtime status (whether PID is active).
     */
    get: operations["listChannels"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/status/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Channels Status
     * @description Get comprehensive status for all enabled channels at once.
     *
     *     Returns detailed channel status including heater output state, PID controller
     *     state, temperature readings, and error statistics for each enabled channel.
     */
    get: operations["getAllChannelsStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{channel_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Channel Info
     * @description Get information about a specific channel.
     *
     *     Returns configuration and runtime status for the specified channel.
     */
    get: operations["getChannelInfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/channels/{channel_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Channel Status
     * @description Get comprehensive real-time status for a specific channel.
     *
     *     Returns:
     *     - channel_id, channel_name: Channel identity
     *     - current_temp: Latest temperature reading in °C
     *     - heater: Real-time heater output (power fraction, measured watts, type, metadata)
     *     - pid: PID controller state (active, target, parameters, variables, timing, errors)
     */
    get: operations["getChannelStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/{channel_id}/target-temp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Target Temp
     * @description Get the current target temperature for a specific channel.
     */
    get: operations["getTargetTemp"];
    put?: never;
    /**
     * Set Target Temp
     * @description Set a new target temperature for a specific channel.
     */
    post: operations["setTargetTemp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/{channel_id}/pid-parameters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pid Parameters
     * @description Get the current PID parameters for a specific channel.
     */
    get: operations["getPidParameters"];
    put?: never;
    /**
     * Set Pid Parameters
     * @description Update PID parameters for a specific channel.
     */
    post: operations["setPidParameters"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/{channel_id}/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get All Config
     * @description Get all configuration (target temperature and PID parameters) for a specific channel.
     */
    get: operations["getAllConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pid/{channel_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Pid
     * @description Start the PID controller for a specific channel.
     */
    post: operations["startPID"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pid/{channel_id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stop Pid
     * @description Stop the PID controller for a specific channel.
     */
    post: operations["stopPID"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pid/{channel_id}/manual-power": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set Manual Power
     * @description Manually set heater power for a specific channel.
     *
     *     Stops the PID controller if it is currently running.
     *     Power is a normalized value between 0.0 and 1.0.
     */
    post: operations["setManualPower"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AllChannelsStatus
     * @description Status of all channels at once.
     */
    AllChannelsStatus: {
      /** Channels */
      channels: components["schemas"]["ChannelStatusOut"][];
    };
    /**
     * ChannelInfo
     * @description Channel information with runtime status.
     */
    ChannelInfo: {
      /** Channelid */
      channelId: number;
      /** Name */
      name: string;
      /** Thermochannel */
      thermoChannel: number;
      /**
       * Heatertype
       * @description Heater type: gpio, psu, or mock
       */
      heaterType: string;
      /** Enabled */
      enabled: boolean;
      /**
       * Maxpowerwatts
       * @description Maximum heater power in watts
       */
      maxPowerWatts: number;
      /**
       * Isactive
       * @description Whether PID controller is currently active
       * @default false
       */
      isActive: boolean;
    };
    /**
     * ChannelListResponse
     * @description List of all configured channels.
     */
    ChannelListResponse: {
      /** Channels */
      channels: components["schemas"]["ChannelInfo"][];
    };
    /**
     * ChannelStatusOut
     * @description Comprehensive real-time status for a single heater channel.
     *
     *     Combines channel identity, the current temperature reading,
     *     heater output state, and PID controller state into one response.
     */
    ChannelStatusOut: {
      /**
       * Channelid
       * @description Unique channel identifier from configuration.
       */
      channelId: number;
      /**
       * Channelname
       * @description Human-readable channel name.
       */
      channelName: string;
      /**
       * Currenttemp
       * @description Latest temperature reading in °C from the associated Lakeshore thermometer channel. Null if no reading yet.
       */
      currentTemp?: number | null;
      /** @description Real-time heater output state including power level, measured watts, and type-specific metadata. */
      heater: components["schemas"]["HeaterStatus"];
      /** @description PID controller state including target, parameters, internal variables, timing, and error statistics. */
      pid: components["schemas"]["PidStatus"];
    };
    /**
     * ConfigAll
     * @description Schema for all configuration data.
     *
     *     Contains target temperature and PID parameters.
     */
    ConfigAll: {
      /** Targettemp */
      targetTemp: number;
      pidParameters: components["schemas"]["Parameters"];
    };
    /**
     * ErrorStats
     * @description Schema for error statistics.
     *
     *     Tracks API call errors over different time periods.
     */
    ErrorStats: {
      /** Errorslast1M */
      errorsLast1M: number;
      /** Errorslast10M */
      errorsLast10M: number;
      /** Errorssincestart */
      errorsSinceStart: number;
      /** Lasterrormessage */
      lastErrorMessage: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HeaterStatus
     * @description Real-time heater output state.
     *
     *     Reports the current power level and heater-type-specific metadata.
     */
    HeaterStatus: {
      /**
       * Power
       * @description Requested heater output level as a fraction (0.0 to 1.0). Reflects the value set by PID or manual control.
       */
      power: number;
      /**
       * Powerwatts
       * @description Actual heater power in watts. For PSU heaters this is measured via voltage × current; for GPIO/Mock heaters it is calculated from the configured max power.
       */
      powerWatts: number;
      /**
       * Heatertype
       * @description Heater type identifier: 'gpio', 'psu', or 'mock'.
       */
      heaterType: string;
      /**
       * Heatermetadata
       * @description Heater-type-specific metadata. PSU: measured_voltage, measured_current, max_voltage, max_current, max_wattage. GPIO/Mock: empty.
       * @default {}
       */
      heaterMetadata: {
        [key: string]: unknown;
      };
    };
    /**
     * ManualPower
     * @description Schema for manual power control.
     *
     *     Power is a normalized value between 0.0 and 1.0.
     */
    ManualPower: {
      /** Power */
      power: number;
    };
    /**
     * Parameters
     * @description Schema for temperature parameters.
     *
     *     Used by GET and PUT /temp/parameters endpoints
     *     to retrieve or update temperature parameters.
     */
    Parameters: {
      /**
       * Kp
       * @default 1
       */
      kp: number;
      /**
       * Ki
       * @default 0
       */
      ki: number;
      /**
       * Kd
       * @default 0
       */
      kd: number;
    };
    /**
     * PidStatus
     * @description PID controller state.
     *
     *     Contains whether the PID loop is running, its target, tuning parameters,
     *     internal variables, timing information, and error statistics.
     */
    PidStatus: {
      /**
       * Isactive
       * @description Whether the PID control loop is currently running.
       */
      isActive: boolean;
      /**
       * Target
       * @description Target temperature in °C that the PID is tracking.
       */
      target: number;
      /**
       * Startedat
       * @description UTC timestamp when the PID loop was started. Null if PID has never been started or was stopped.
       */
      startedAt?: string | null;
      /**
       * Runningforseconds
       * @description Elapsed seconds since the PID loop was started. Null when PID is not active.
       */
      runningForSeconds?: number | null;
      /** @description Current PID tuning coefficients (Kp, Ki, Kd). */
      parameters: components["schemas"]["Parameters"];
      /** @description Internal PID state: integral accumulator, last error, and last temperature measurement. */
      variables: components["schemas"]["PidVariables"];
      /** @description Error counters for thermometer API read failures over 1 min, 10 min, and since PID start. */
      errorStats: components["schemas"]["ErrorStats"];
      /** @description Why PID was last automatically stopped (overheat or sensor_timeout). Null when never auto-stopped, manually stopped, or running. Cleared on next Start or on manual Stop. */
      lastStopReason?: components["schemas"]["PidStopReason"] | null;
      /**
       * Laststopat
       * @description UTC timestamp the auto-stop fired. Null when last_stop_reason is null.
       */
      lastStopAt?: string | null;
      /**
       * Laststopdetail
       * @description Human-readable detail (e.g. measured °C vs limit, or seconds since last read).
       */
      lastStopDetail?: string | null;
    };
    /**
     * PidStopReason
     * @description Reason the PID loop was automatically stopped by a safety check.
     * @enum {string}
     */
    PidStopReason: "overheat" | "sensor_timeout";
    /**
     * PidVariables
     * @description Schema for PID internal variables.
     *
     *     Contains the interval variables used in PID calculations.
     */
    PidVariables: {
      /** Integral */
      integral: number;
      /** Lasterror */
      lastError: number;
      /** Lastmeasurement */
      lastMeasurement: number | null;
    };
    /**
     * TargetTemp
     * @description Schema for target temperature.
     *
     *     Used by GET and PUT /temp/target-temp endpoints
     *     to retrieve or update target temperature.
     */
    TargetTemp: {
      /** Target */
      target: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listChannels: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelListResponse"];
        };
      };
    };
  };
  getAllChannelsStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AllChannelsStatus"];
        };
      };
    };
  };
  getChannelInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getChannelStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChannelStatusOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getTargetTemp: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TargetTemp"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  setTargetTemp: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetTemp"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getPidParameters: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Parameters"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  setPidParameters: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Parameters"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Parameters"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  getAllConfig: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigAll"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  startPID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stopPID: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  setManualPower: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        channel_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ManualPower"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
