# coding: utf-8

# flake8: noqa
"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from simulator_client.models.get_simulator_temperature200_response import GetSimulatorTemperature200Response
from simulator_client.models.get_simulator_temperature404_response import GetSimulatorTemperature404Response
from simulator_client.models.set_heater_output200_response import SetHeaterOutput200Response
from simulator_client.models.set_heater_output404_response import SetHeaterOutput404Response
from simulator_client.models.set_heater_output_request import SetHeaterOutputRequest

