# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1(BaseModel):
    """
    GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1
    """ # noqa: E501
    type: StrictStr
    position: Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=2, max_length=2)]
    name: StrictStr
    heater_pin: Union[StrictFloat, StrictInt] = Field(alias="heaterPin")
    heater_power: Union[StrictFloat, StrictInt] = Field(alias="heaterPower")
    initial_power: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, alias="initialPower")
    __properties: ClassVar[List[str]] = ["type", "position", "name", "heaterPin", "heaterPower", "initialPower"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['heater']):
            raise ValueError("must be one of enum values ('heater')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "position": obj.get("position"),
            "name": obj.get("name"),
            "heaterPin": obj.get("heaterPin"),
            "heaterPower": obj.get("heaterPower"),
            "initialPower": obj.get("initialPower")
        })
        return _obj


