# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from simulator_client.models.get_all_states200_response_simulators_inner_config_instruments_inner import GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInner
from typing import Optional, Set
from typing_extensions import Self

class GetAllStates200ResponseSimulatorsInnerConfig(BaseModel):
    """
    GetAllStates200ResponseSimulatorsInnerConfig
    """ # noqa: E501
    name: StrictStr
    enabled: StrictBool
    size: Annotated[List[Union[StrictFloat, StrictInt]], Field(min_length=2, max_length=2)]
    instruments: List[GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInner]
    external_temperature: Union[StrictFloat, StrictInt] = Field(alias="externalTemperature")
    external_conductivity: Union[StrictFloat, StrictInt] = Field(alias="externalConductivity")
    internal_conductivity: Union[StrictFloat, StrictInt] = Field(alias="internalConductivity")
    __properties: ClassVar[List[str]] = ["name", "enabled", "size", "instruments", "externalTemperature", "externalConductivity", "internalConductivity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAllStates200ResponseSimulatorsInnerConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instruments (list)
        _items = []
        if self.instruments:
            for _item_instruments in self.instruments:
                if _item_instruments:
                    _items.append(_item_instruments.to_dict())
            _dict['instruments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAllStates200ResponseSimulatorsInnerConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "enabled": obj.get("enabled"),
            "size": obj.get("size"),
            "instruments": [GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInner.from_dict(_item) for _item in obj["instruments"]] if obj.get("instruments") is not None else None,
            "externalTemperature": obj.get("externalTemperature"),
            "externalConductivity": obj.get("externalConductivity"),
            "internalConductivity": obj.get("internalConductivity")
        })
        return _obj


