# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simulator_client.models.get_all_states200_response_simulators_inner import GetAllStates200ResponseSimulatorsInner

class TestGetAllStates200ResponseSimulatorsInner(unittest.TestCase):
    """GetAllStates200ResponseSimulatorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllStates200ResponseSimulatorsInner:
        """Test GetAllStates200ResponseSimulatorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllStates200ResponseSimulatorsInner`
        """
        model = GetAllStates200ResponseSimulatorsInner()
        if include_optional:
            return GetAllStates200ResponseSimulatorsInner(
                config = simulator_client.models.get_all_states_200_response_simulators_inner_config.getAllStates_200_response_simulators_inner_config(
                    name = '', 
                    enabled = True, 
                    size = [
                        1.337
                        ], 
                    instruments = [
                        null
                        ], 
                    external_temperature = 1.337, 
                    external_conductivity = 1.337, 
                    internal_conductivity = 1.337, ),
                state = [
                    [
                        1.337
                        ]
                    ]
            )
        else:
            return GetAllStates200ResponseSimulatorsInner(
                config = simulator_client.models.get_all_states_200_response_simulators_inner_config.getAllStates_200_response_simulators_inner_config(
                    name = '', 
                    enabled = True, 
                    size = [
                        1.337
                        ], 
                    instruments = [
                        null
                        ], 
                    external_temperature = 1.337, 
                    external_conductivity = 1.337, 
                    internal_conductivity = 1.337, ),
                state = [
                    [
                        1.337
                        ]
                    ],
        )
        """

    def testGetAllStates200ResponseSimulatorsInner(self):
        """Test GetAllStates200ResponseSimulatorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
