# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simulator_client.models.set_heater_output404_response import SetHeaterOutput404Response

class TestSetHeaterOutput404Response(unittest.TestCase):
    """SetHeaterOutput404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetHeaterOutput404Response:
        """Test SetHeaterOutput404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetHeaterOutput404Response`
        """
        model = SetHeaterOutput404Response()
        if include_optional:
            return SetHeaterOutput404Response(
                error = 'Pin not found'
            )
        else:
            return SetHeaterOutput404Response(
                error = 'Pin not found',
        )
        """

    def testSetHeaterOutput404Response(self):
        """Test SetHeaterOutput404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
