# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simulator_client.api.simulator_api import SimulatorApi


class TestSimulatorApi(unittest.TestCase):
    """SimulatorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SimulatorApi()

    def tearDown(self) -> None:
        pass

    def test_get_simulator_temperature(self) -> None:
        """Test case for get_simulator_temperature

        Get Simulator Temperature
        """
        pass

    def test_set_heater_output(self) -> None:
        """Test case for set_heater_output

        Set Heater Output
        """
        pass


if __name__ == '__main__':
    unittest.main()
