# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simulator_client.models.get_all_states200_response_simulators_inner_config_instruments_inner_any_of1 import GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1

class TestGetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1(unittest.TestCase):
    """GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1:
        """Test GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1`
        """
        model = GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1()
        if include_optional:
            return GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1(
                type = 'heater',
                position = [
                    1.337
                    ],
                name = '',
                heater_pin = 1.337,
                heater_power = 1.337
            )
        else:
            return GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1(
                type = 'heater',
                position = [
                    1.337
                    ],
                name = '',
                heater_pin = 1.337,
                heater_power = 1.337,
        )
        """

    def testGetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1(self):
        """Test GetAllStates200ResponseSimulatorsInnerConfigInstrumentsInnerAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
