# coding: utf-8

"""
    Simulator (LT Capstone)

    Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from simulator_client.models.get_simulator_temperature200_response import GetSimulatorTemperature200Response

class TestGetSimulatorTemperature200Response(unittest.TestCase):
    """GetSimulatorTemperature200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSimulatorTemperature200Response:
        """Test GetSimulatorTemperature200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSimulatorTemperature200Response`
        """
        model = GetSimulatorTemperature200Response()
        if include_optional:
            return GetSimulatorTemperature200Response(
                temperature = 1.337,
                celcius = 1.337
            )
        else:
            return GetSimulatorTemperature200Response(
                temperature = 1.337,
                celcius = 1.337,
        )
        """

    def testGetSimulatorTemperature200Response(self):
        """Test GetSimulatorTemperature200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
