# coding: utf-8

"""
    Lakeshore Management API (LT Capstone)

    API server that manages Lakeshore devices and exports metrics via REST API.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from lgg_client.models.coefficients import Coefficients
from lgg_client.models.curve_format import CurveFormat
from typing import Optional, Set
from typing_extensions import Self

class CurveHeader(BaseModel):
    """
    Schema for curve header information containing metadata about a temperature sensor curve.  Used by GET /curve/{channel}/header endpoint to return curve configuration.
    """ # noqa: E501
    curve_name: StrictStr = Field(alias="curveName")
    serial_number: StrictStr = Field(alias="serialNumber")
    curve_data_format: CurveFormat = Field(alias="curveDataFormat")
    temperature_limit: Union[StrictFloat, StrictInt] = Field(alias="temperatureLimit")
    coefficient: Coefficients
    __properties: ClassVar[List[str]] = ["curveName", "serialNumber", "curveDataFormat", "temperatureLimit", "coefficient"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CurveHeader from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CurveHeader from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "curveName": obj.get("curveName"),
            "serialNumber": obj.get("serialNumber"),
            "curveDataFormat": obj.get("curveDataFormat"),
            "temperatureLimit": obj.get("temperatureLimit"),
            "coefficient": obj.get("coefficient")
        })
        return _obj


