# coding: utf-8

"""
    Lakeshore Management API (LT Capstone)

    API server that manages Lakeshore devices and exports metrics via REST API.

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from lgg_client.models.curve_data_point import CurveDataPoint
from typing import Optional, Set
from typing_extensions import Self

class SetCurveDataPointsRequest(BaseModel):
    """
    Schema for setting multiple curve data points at once.  Accepts a list of data points (1 to 200). The existing curve is deleted first, then the supplied points are written starting at index 1. Any remaining slots (up to 200) are left at the device default of (0, 0).
    """ # noqa: E501
    data_points: Annotated[List[CurveDataPoint], Field(min_length=1, max_length=200)] = Field(description="List of curve data points to set (1 to 200). Points are written starting at index 1 in the order provided.", alias="dataPoints")
    __properties: ClassVar[List[str]] = ["dataPoints"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetCurveDataPointsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_points (list)
        _items = []
        if self.data_points:
            for _item_data_points in self.data_points:
                if _item_data_points:
                    _items.append(_item_data_points.to_dict())
            _dict['dataPoints'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetCurveDataPointsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataPoints": [CurveDataPoint.from_dict(_item) for _item in obj["dataPoints"]] if obj.get("dataPoints") is not None else None
        })
        return _obj


