# coding: utf-8

"""
    Lakeshore Management API

    API for Lakeshore Model240 temperature controller

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class StatusResp(BaseModel):
    """
    Schema for device channel status information.  Used by GET /status/{channel} endpoint to return channel status flags.
    """ # noqa: E501
    invalid_reading: StrictBool = Field(alias="invalidReading")
    temp_under_range: StrictBool = Field(alias="tempUnderRange")
    temp_over_range: StrictBool = Field(alias="tempOverRange")
    sensor_units_over_range: StrictBool = Field(alias="sensorUnitsOverRange")
    sensor_units_under_range: StrictBool = Field(alias="sensorUnitsUnderRange")
    __properties: ClassVar[List[str]] = ["invalidReading", "tempUnderRange", "tempOverRange", "sensorUnitsOverRange", "sensorUnitsUnderRange"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusResp from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusResp from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "invalidReading": obj.get("invalidReading"),
            "tempUnderRange": obj.get("tempUnderRange"),
            "tempOverRange": obj.get("tempOverRange"),
            "sensorUnitsOverRange": obj.get("sensorUnitsOverRange"),
            "sensorUnitsUnderRange": obj.get("sensorUnitsUnderRange")
        })
        return _obj


